### Accessing/Changing specific elements, rows, columns etc

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
# get a specific element [r, c]
a[1,-2]

13

In [6]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [13]:
a[1,5] =20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


##### 3d Array

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
#Get Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [22]:
#replace
b[:,1,:]=[[9,8],[7,6]]
print(b)

[[[1 2]
  [9 8]]

 [[5 6]
  [7 6]]]
