### Basics of Numpy

In [2]:
import numpy as np

In [18]:
a = np.array([1,2,3], dtype='int16') #can specify dtype
a

array([1, 2, 3], dtype=int16)

#### See Below the example of Fixed Datatype of Numpy array. 
##### 3 is int and rest are float but 3 is also converted to float

In [20]:
b = np.array([[9.,6.,3.],[5.,3,5.]])
print(b)

[[9. 6. 3.]
 [5. 3. 5.]]


In [7]:
# Get Dimension
b.ndim

2

In [10]:
# Get Shape
b.shape

(2, 3)

In [14]:
# Get Type
b.dtype

dtype('float64')

In [8]:
# Get Size
b.itemsize

8

In [19]:
# Get Total Size
a.size * a.itemsize
a.nbytes

6